### ISSUE TITLE
我有个地方没写好

### ISSUE THREAD

**Issue by ustcw0ng** [Ubpa/USTC_CG#3]
在\0_CppPratices\project\src\executables\3_TemplateDArray（\0_CppPratices\samples\src\executables\3_TemplateDArray）中，我在DArray.h和DArray.inl添加了如下类型转换函数声明和函数
public:template <typename To_do>
	operator DArray<To_do>();

template <typename T>
template <typename To_do>
DArray<T>::operator DArray<To_do>(){
	DArray<To_do> doing;
	doing.SetSize(m_nMax);
	for (size_t i = m_nMax; i > m_nSize; i--)
	 	doing.DeleteAt(i);
	for (size_t i = 0; i < m_nSize; i++)
		doing.SetAt(i,(To_do)m_pData[i]);;
	return doing;
};
但我函数里无法调用DArray<To_do> doing的private部分，您能帮我看看能怎样改吗

**Comment by ustcw0ng** [comment]
复制的有点问题 三处template应改为
template <typename To_do>
template <typename T>
template <typename To_do>

**Comment by ustcw0ng** [comment]
复制的有点问题（好像有bug） 三处template应改为
template <typename To_do>
template <typename T>
template <typename To_do>

**Comment by ustcw0ng** [comment]
复制的有点问题 三处template应改为
template typename To_do
template typename T
template typename To_do
(三角括号和三角括号内的内容好像无法显示)

**Comment by Ubpa** [comment]
在DArray 的定义中写上 `friend`
```c++
template<typename T>
class DArray{
  template<typename U>
  friend class DArray;
  //...
}
```
