### ISSUE TITLE
没搞懂.ui怎么编辑来改大小

### ISSUE THREAD

**Issue by Wongboo** [Ubpa/USTC_CG#6]
![image](https://user-images.githubusercontent.com/44860323/87008997-20d2f300-c1f7-11ea-84bb-285dc61a7298.png)
![image](https://user-images.githubusercontent.com/44860323/87009008-27616a80-c1f7-11ea-840c-93aa4e6f6653.png)
![image](https://user-images.githubusercontent.com/44860323/87009013-2a5c5b00-c1f7-11ea-9f1f-fee2ac6fa8df.png)
       图二是我原来的构思，图一是做出来的效果（菜单栏右对齐有三个点，打开是关于和帮助），但——正如图三所指出的，它的状态栏和菜单栏都太小了。
       于是我尝试在MiniDraw.ui里调整大小，对象Minidraw里面有三个子对象centralWidget、menuBar、statusBar，但遗憾的是centralWidget好像怎么也调不小，无论是调整geometry还是sizepolicy都不行，即使在viewwidget.ui里也不行，直接导致了状态栏和菜单栏都放不大，最后看起来比例失调。
       望赐教！

**Comment by Ubpa** [comment]
我也不是 Qt 专家，这种事情主要看文档。我查到的资料是菜单栏会根据内部的内容调整大小，尝试扩大 icon 的大小看看？

**Comment by JianqiangDing** [comment]
路人甲建议如果作业重点不是交互的话，写UI用[imgui](https://github.com/ocornut/imgui)吧，省事儿很多，多花时间研究其他重要的东西路人甲觉得更重要些

**Comment by ustcw0ng** [comment]
> 我也不是 Qt 专家，这种事情主要看文档。我查到的资料是菜单栏会根据内部的内容调整大小，尝试扩大 icon 的大小看看？

没用啊，这个操作的目的是让4个字符的按钮宽度能更大（而不是只适应四个字符的大小），也就是说让按钮横向更大，无法让菜单栏（或者说按钮）竖向更大

**Comment by ustcw0ng** [comment]
我之前看minidraw里的viewwidget也没想到，现在自己也写多态觉得里面shape_中每次都new一个地址，却从来没有释放，是不是有些问题呢
