### ISSUE TITLE
跨平台的一系列问题

### ISSUE THREAD

**Issue by Wongboo** [Ubpa/USTC_CG#7]
我现在在学习USTC-CG课程中，遇到了很多cmake跨平台的问题，我已经尽力修改，把他们汇总一下，UEngine在跨平台问题上有很多问题没有办法全部修改。  
1.
    更新前的USTC_CG/Homeworks/0_CppPratices/project/cmake/UbpaTool.cmake
    更新前的USTC_CG/Homeworks/0_CppPratices/samples/cmake/UbpaTool.cmake
    更新后无此问题
    若不改，只有MSVC能运行，GCC，clang不行
    RUNTIME DESTINATION "bin"
    加一句LIBRARY DESTINATION "lib/${FOLDER_NAME}"
    ARCHIVE DESTINATION "lib/${FOLDER_NAME}"
2.
   OpenCV相关
    若不改，只有Windows能运行，因为Windows上opencv的目录架构和其他的opencv略有不同
    find_package(OpenCV REQUIRED)后加一句include_directories(${OpenCV_INCLUDE_DIRS})
    若不改，只有编译（或者安装的二进制文件预编译）cmake时打开输出opencv_world库的开关才能编译
    openCV_world 改为 ${OpenCV_LIBS}
3.OpenMP相关
   USTC_CG/Homeworks/4_MinSurfMeshPara/project/CMakeLists.txt中的127-133行建议改为
  find_package(OpenMP REQUIRED)
	link_libraries(OpenMP::OpenMP_CXX)
（当然也可以，Ubpa_AddTarget中的LIBS加上OpenMP::OpenMP_CXX）
  否则在clang下，即使取消了127-133行的注释依旧无法找到omp.h
4.UEngine相关
  https://github.com/Ubpa/USTC_CG/blob/master/Homeworks/4_MinSurfMeshPara/project/setup.md中的Ubpa_20200318.zip中的UGM/include/UGM/Interfaces/IMatrix/IMatrix.h中inline static const Impl zero() noexcept中
内联静态函数用了this指针，但若按标准，非静态函数才能使用this指针，于是clang下还是没法编译，当然在新版的UGM下没有这个问题，但目录架构有点不一样，没想好怎么改成新版，如果需要，还可以说一下UEngine其他的跨平台问题，我现在暂时还没法用clang编译成功，报的错过于多了

**Comment by Ubpa** [comment]
不做跨平台

**Comment by ustcw0ng** [comment]
感觉不跨平台没必要cmake吧

**Comment by Ubpa** [comment]
一个项目会有很多依赖项，不是说给一个 sln 就完事了

**Comment by Ubpa** [comment]
应该将 cmake 看成是工程搭建工具，而不是仅为了跨平台

**Comment by ustcw0ng** [comment]
有点没明白Uengine怎么打开文件，极小曲面和纹理都写好了
