### ISSUE TITLE
HW_9 编译不成功

### ISSUE THREAD

**Issue by Wongboo** [Ubpa/USTC_CG#8]
Homework 9 编译时会提示_deps/uscene-src/include/UScene/core/Cmpt中有h文件想要include， detail/dynamic_reflection/...，然而我重复尝试了多次，也在相关库里搜索，只在UScene的.gitignore中有dynamic_reflection的字段。
（HW4里的Uengine我貌似一直未能搞懂从那个按钮开始加载.obj文件，我的cmake成功加载了assimp和tinyxml2的库，故现在也没有把HW4，HW5调试，HW6也因此一直搁浅）
望解惑，谢谢

**Comment by Ubpa** [comment]
通过邮件发我联系方式，在 QQ 上谈

**Comment by Ubpa** [comment]
ustczt@mail.ustc.edu.cn
