### ISSUE TITLE
C++练习2——EfficientDArray答案有误

### ISSUE THREAD

**Issue by jinjin2017c** [Ubpa/USTC_CG#9]
**文件位置**：Homeworks\0_CppPratices\samples\src\executables\2_EfficientDArray\DArray.cpp

**问题描述**：初始化时，变量m_nMax设置为0，pushback函数和insert函数对数组扩容时，直接通过m_nMax *= 2来实现，导致对空数组进行这两个操作时，陷入死循环

**修改意见**：改为 m_nMax = (m_nMax == 0 ? 1 : m_nMax * 2);

**Comment by Ubpa** [comment]
Thanks!
